# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: debe9ea2357000b312017c0ef5f5ea2dd4c9b45dd86b48d70574fc3859c6286d1c33f5430fbd977c7509ecc18af923670185443024e96abef4a441f15a8f4c8c

test:
  secret_key_base: 2494c90c1f6f429d09db1b8bebe7647e09a50020983aad5491eec16f0447d474ab5e7a1f4f8d077698cf6ab0268408591b10a0e52c91d6397f797d2077a7e31d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
